site_name: Extra Gestão
site_author: José
site_description: Site voltado para a documentação do Grupo Extra Gestão em Requisitos de Software
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T02-ExtraGestao
repo_name: 2025.1-T02-ExtraGestao

nav:
  - Sobre: index.md
  - "Visão de Produto e Projeto":
      - "Cenário Atual do Cliente e do Negócio": vpp/cenario-atual-do-cliente-e-do-negocio.md
      - "Solução Proposta" : vpp/solucao-proposta.md
      - "Estratégias de Engenharia de Eoftware" : vpp/estrategias-de-engenharia-de-software.md
      

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  disable_nav_previous_next: true

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Trocar para modo escuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Trocar para modo claro

  favicon: assets/favicon.ico
  logo: assets/favicon.ico

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css: [stylesheets/extra.css]